// lib/feature/games/chat_games/rate_it/rate_topic_pool.dart
//
// Rate It topic pool: 1000 things both players rate from 1 to 10.
// The first 30 entries mirror rate_topics.dart so old games still resolve.
// Ids are stable: never rename or reuse one, only append new topics.

class RateTopicData {
  final String id;
  final String emoji;
  final String label;

  const RateTopicData(this.id, this.emoji, this.label);
}

class RateTopicPool {
  RateTopicPool._();

  static const List<RateTopicData> pool = [
    RateTopicData('pineapple_pizza', '🍍', 'Pineapple on pizza'),
    RateTopicData('horror', '👻', 'Horror movies'),
    RateTopicData('six_am', '⏰', 'Waking up at 6 AM'),
    RateTopicData('road_trips', '🚗', 'Long road trips'),
    RateTopicData('spicy', '🌶️', 'Very spicy food'),
    RateTopicData('public_dance', '💃', 'Dancing in public'),
    RateTopicData('rain', '🌧️', 'Rainy days'),
    RateTopicData('cats', '🐱', 'Cats'),
    RateTopicData('dogs', '🐶', 'Dogs'),
    RateTopicData('bollywood', '🎶', 'Old Bollywood songs'),
    RateTopicData('gym', '🏋️', 'Going to the gym'),
    RateTopicData('shopping', '🛍️', 'Shopping'),
    RateTopicData('camping', '⛺', 'Camping'),
    RateTopicData('street_food', '🌮', 'Street food'),
    RateTopicData('cricket', '🏏', 'Watching cricket'),
    RateTopicData('surprise_party', '🎉', 'Surprise parties'),
    RateTopicData('reality_tv', '📺', 'Reality shows'),
    RateTopicData('sleep_in', '😴', 'Sleeping in on Sunday'),
    RateTopicData('coffee', '☕', 'Coffee'),
    RateTopicData('chai', '🫖', 'Chai'),
    RateTopicData('mountains', '🏔️', 'Mountain trips'),
    RateTopicData('beaches', '🏖️', 'Beach holidays'),
    RateTopicData('video_games', '🎮', 'Video games'),
    RateTopicData('cooking', '👩‍🍳', 'Cooking at home'),
    RateTopicData('karaoke', '🎤', 'Karaoke nights'),
    RateTopicData('astrology', '✨', 'Astrology'),
    RateTopicData('selfies', '🤳', 'Taking selfies'),
    RateTopicData('voice_notes', '🎙️', 'Voice notes'),
    RateTopicData('books', '📚', 'Reading books'),
    RateTopicData('weddings', '💒', 'Big fat weddings'),
    RateTopicData('biryani', '🍛', 'Biryani'),
    RateTopicData('momos', '🥟', 'Momos'),
    RateTopicData('sushi', '🍣', 'Sushi'),
    RateTopicData('pizza', '🍕', 'Pizza'),
    RateTopicData('burgers', '🍔', 'Burgers'),
    RateTopicData('pani_puri', '🍢', 'Pani puri'),
    RateTopicData('dosa', '🥞', 'Masala dosa'),
    RateTopicData('idli_sambar', '🍚', 'Idli sambar'),
    RateTopicData('butter_chicken', '🧈', 'Butter chicken'),
    RateTopicData('paneer_tikka', '🧀', 'Paneer tikka'),
    RateTopicData('dal_chawal', '🍲', 'Dal chawal'),
    RateTopicData('rajma_chawal', '🫘', 'Rajma chawal'),
    RateTopicData('chole_bhature', '🫓', 'Chole bhature'),
    RateTopicData('aloo_paratha', '🥔', 'Aloo paratha'),
    RateTopicData('vada_pav', '🍔', 'Vada pav'),
    RateTopicData('pav_bhaji', '🍞', 'Pav bhaji'),
    RateTopicData('maggi', '🍜', 'Instant noodles'),
    RateTopicData('ramen', '🍜', 'Ramen'),
    RateTopicData('pasta', '🍝', 'Pasta'),
    RateTopicData('mac_cheese', '🧀', 'Mac and cheese'),
    RateTopicData('tacos', '🌮', 'Tacos'),
    RateTopicData('burritos', '🌯', 'Burritos'),
    RateTopicData('nachos', '🧀', 'Nachos'),
    RateTopicData('shawarma', '🥙', 'Shawarma'),
    RateTopicData('falafel', '🧆', 'Falafel'),
    RateTopicData('hummus', '🫓', 'Hummus'),
    RateTopicData('dim_sum', '🥟', 'Dim sum'),
    RateTopicData('fried_rice', '🍙', 'Fried rice'),
    RateTopicData('hakka_noodles', '🥢', 'Hakka noodles'),
    RateTopicData('manchurian', '🥡', 'Gobi manchurian'),
    RateTopicData('spring_rolls', '🌯', 'Spring rolls'),
    RateTopicData('pad_thai', '🥡', 'Pad thai'),
    RateTopicData('thai_curry', '🥥', 'Thai green curry'),
    RateTopicData('korean_bbq', '🍲', 'Korean BBQ'),
    RateTopicData('kimchi', '🥬', 'Kimchi'),
    RateTopicData('pho', '🍲', 'Pho'),
    RateTopicData('dumplings', '🥟', 'Dumplings'),
    RateTopicData('samosa', '🥟', 'Samosas'),
    RateTopicData('pakode', '🧅', 'Pakode in the rain'),
    RateTopicData('kachori', '🥮', 'Kachori'),
    RateTopicData('jalebi', '🧡', 'Jalebi'),
    RateTopicData('gulab_jamun', '🍮', 'Gulab jamun'),
    RateTopicData('rasmalai', '🥛', 'Rasmalai'),
    RateTopicData('kaju_katli', '🟨', 'Kaju katli'),
    RateTopicData('gajar_halwa', '🥕', 'Gajar halwa'),
    RateTopicData('kheer', '🍚', 'Kheer'),
    RateTopicData('kulfi', '🍦', 'Kulfi'),
    RateTopicData('ice_cream', '🍨', 'Ice cream'),
    RateTopicData('gelato', '🍦', 'Gelato'),
    RateTopicData('brownies', '🍫', 'Brownies'),
    RateTopicData('cheesecake', '🍰', 'Cheesecake'),
    RateTopicData('donuts', '🍩', 'Donuts'),
    RateTopicData('croissants', '🥐', 'Croissants'),
    RateTopicData('cupcakes', '🧁', 'Cupcakes'),
    RateTopicData('cookies', '🍪', 'Cookies'),
    RateTopicData('waffles', '🧇', 'Waffles'),
    RateTopicData('pancakes', '🥞', 'Pancakes'),
    RateTopicData('dark_chocolate', '🍫', 'Dark chocolate'),
    RateTopicData('white_chocolate', '🤍', 'White chocolate'),
    RateTopicData('nutella', '🌰', 'Nutella'),
    RateTopicData('peanut_butter', '🥜', 'Peanut butter'),
    RateTopicData('marshmallows', '🍡', 'Marshmallows'),
    RateTopicData('cotton_candy', '🍭', 'Cotton candy'),
    RateTopicData('popcorn', '🍿', 'Popcorn'),
    RateTopicData('caramel_popcorn', '🍯', 'Caramel popcorn'),
    RateTopicData('french_fries', '🍟', 'French fries'),
    RateTopicData('onion_rings', '🧅', 'Onion rings'),
    RateTopicData('potato_chips', '🥔', 'Potato chips'),
    RateTopicData('garlic_bread', '🥖', 'Garlic bread'),
    RateTopicData('grilled_cheese', '🥪', 'Grilled cheese sandwich'),
    RateTopicData('avocado_toast', '🥑', 'Avocado toast'),
    RateTopicData('salads', '🥗', 'Salads'),
    RateTopicData('smoothie_bowls', '🥣', 'Smoothie bowls'),
    RateTopicData('oatmeal', '🥣', 'Oatmeal for breakfast'),
    RateTopicData('cereal', '🥣', 'Cereal'),
    RateTopicData('poha', '🍛', 'Poha'),
    RateTopicData('upma', '🍚', 'Upma'),
    RateTopicData('eggs_breakfast', '🍳', 'Eggs for breakfast'),
    RateTopicData('omelette', '🍳', 'Masala omelette'),
    RateTopicData('khichdi', '🍲', 'Khichdi'),
    RateTopicData('curd_rice', '🍚', 'Curd rice'),
    RateTopicData('pickles', '🫙', 'Achaar with everything'),
    RateTopicData('papad', '🫓', 'Papad'),
    RateTopicData('raita', '🥒', 'Raita'),
    RateTopicData('green_chutney', '🌿', 'Green chutney'),
    RateTopicData('ketchup', '🍅', 'Ketchup on everything'),
    RateTopicData('mayo', '🥚', 'Mayonnaise'),
    RateTopicData('sriracha', '🌶️', 'Sriracha'),
    RateTopicData('mustard', '🟡', 'Mustard'),
    RateTopicData('olives', '🫒', 'Olives'),
    RateTopicData('mushrooms', '🍄', 'Mushrooms'),
    RateTopicData('broccoli', '🥦', 'Broccoli'),
    RateTopicData('brinjal', '🍆', 'Brinjal'),
    RateTopicData('bitter_gourd', '🥒', 'Karela'),
    RateTopicData('okra', '🫛', 'Bhindi'),
    RateTopicData('paneer', '🧀', 'Paneer anything'),
    RateTopicData('tofu', '⬜', 'Tofu'),
    RateTopicData('coriander', '🌿', 'Coriander'),
    RateTopicData('garlic', '🧄', 'Garlic'),
    RateTopicData('onions_raw', '🧅', 'Raw onions'),
    RateTopicData('coconut', '🥥', 'Coconut'),
    RateTopicData('mango', '🥭', 'Mangoes'),
    RateTopicData('watermelon', '🍉', 'Watermelon'),
    RateTopicData('pineapple', '🍍', 'Pineapple'),
    RateTopicData('strawberries', '🍓', 'Strawberries'),
    RateTopicData('bananas', '🍌', 'Bananas'),
    RateTopicData('apples', '🍎', 'Apples'),
    RateTopicData('grapes', '🍇', 'Grapes'),
    RateTopicData('oranges', '🍊', 'Oranges'),
    RateTopicData('papaya', '🍈', 'Papaya'),
    RateTopicData('guava', '🍐', 'Guava with chilli salt'),
    RateTopicData('lychee', '🍒', 'Lychee'),
    RateTopicData('kiwi', '🥝', 'Kiwi'),
    RateTopicData('pomegranate', '❤️', 'Pomegranate'),
    RateTopicData('jackfruit', '🍈', 'Jackfruit'),
    RateTopicData('durian', '😵', 'Durian'),
    RateTopicData('dates_fruit', '🌴', 'Dates'),
    RateTopicData('dry_fruits', '🥜', 'Dry fruits'),
    RateTopicData('cheese', '🧀', 'Cheese'),
    RateTopicData('blue_cheese', '🧀', 'Blue cheese'),
    RateTopicData('seafood', '🦐', 'Seafood'),
    RateTopicData('fish_curry', '🐟', 'Fish curry'),
    RateTopicData('prawns', '🦐', 'Prawns'),
    RateTopicData('fried_chicken', '🍗', 'Fried chicken'),
    RateTopicData('kebabs', '🍢', 'Kebabs'),
    RateTopicData('tandoori', '🔥', 'Tandoori anything'),
    RateTopicData('steak', '🥩', 'Steak'),
    RateTopicData('hot_dogs', '🌭', 'Hot dogs'),
    RateTopicData('sandwiches', '🥪', 'Sandwiches'),
    RateTopicData('wraps', '🌯', 'Wraps and rolls'),
    RateTopicData('kathi_roll', '🌯', 'Kathi rolls'),
    RateTopicData('frankie', '🫔', 'Frankie'),
    RateTopicData('thali', '🍛', 'Thali meals'),
    RateTopicData('buffets', '🍽️', 'Buffets'),
    RateTopicData('tasting_menus', '🍽️', 'Tasting menus'),
    RateTopicData('fine_dining', '🕯️', 'Fine dining'),
    RateTopicData('food_trucks', '🚚', 'Food trucks'),
    RateTopicData('dhaba_food', '🛣️', 'Highway dhaba food'),
    RateTopicData('mall_food_court', '🏬', 'Mall food courts'),
    RateTopicData('home_food', '🏠', 'Home-cooked food'),
    RateTopicData('canteen_food', '🍱', 'Canteen food'),
    RateTopicData('airplane_food', '✈️', 'Airplane food'),
    RateTopicData('leftovers', '📦', 'Leftovers'),
    RateTopicData('cold_pizza', '🍕', 'Cold pizza next morning'),
    RateTopicData('spicy_noodles', '🔥', 'Spicy noodle challenge'),
    RateTopicData('mild_food', '😇', 'Mild food'),
    RateTopicData('sweet_curry', '🍯', 'Sweet in curries'),
    RateTopicData('fusion_food', '🧪', 'Fusion food'),
    RateTopicData('tandoori_pizza', '🍕', 'Tandoori paneer pizza'),
    RateTopicData('butter_naan', '🫓', 'Butter naan'),
    RateTopicData('roti', '🫓', 'Fresh rotis'),
    RateTopicData('brown_rice', '🍚', 'Brown rice'),
    RateTopicData('quinoa', '🌾', 'Quinoa'),
    RateTopicData('energy_bars', '🍫', 'Protein bars'),
    RateTopicData('kale', '🥬', 'Kale'),
    RateTopicData('gluten_free', '🌾', 'Gluten-free baking'),
    RateTopicData('vegan_food', '🌱', 'Vegan food'),
    RateTopicData('fast_food', '🍟', 'Fast food'),
    RateTopicData('healthy_eating', '🥗', 'Healthy eating'),
    RateTopicData('cheat_days', '🍰', 'Cheat days'),
    RateTopicData('meal_prep', '🍱', 'Meal prepping'),
    RateTopicData('snacking', '🍿', 'Snacking all day'),
    RateTopicData('midnight_snacks', '🌙', 'Midnight snacks'),
    RateTopicData('breakfast_dinner', '🥞', 'Breakfast for dinner'),
    RateTopicData('skipping_breakfast', '⏭️', 'Skipping breakfast'),
    RateTopicData('brunch', '🥂', 'Brunch'),
    RateTopicData('eating_with_hands', '🙌', 'Eating with hands'),
    RateTopicData('chopsticks', '🥢', 'Using chopsticks'),
    RateTopicData('sharing_food', '🍴', 'Sharing food from plates'),
    RateTopicData('food_photos', '📸', 'Photographing food'),
    RateTopicData('spice_challenges', '🌶️', 'Spice challenges'),
    RateTopicData('mukbang', '🍜', 'Mukbang videos'),
    RateTopicData('cooking_shows', '🍳', 'Cooking shows'),
    RateTopicData('baking', '🧁', 'Baking'),
    RateTopicData('grilling', '🔥', 'Barbecue grilling'),
    RateTopicData('recipe_following', '📖', 'Following recipes exactly'),
    RateTopicData('cooking_by_feel', '🤌', 'Cooking by instinct'),
    RateTopicData('washing_dishes', '🧽', 'Washing dishes'),
    RateTopicData('food_delivery', '🛵', 'Food delivery apps'),
    RateTopicData('trying_new_cuisines', '🌏', 'Trying new cuisines'),
    RateTopicData('same_order', '🔁', 'Ordering the same dish'),
    RateTopicData('pineapple_juice', '🍍', 'Pineapple juice'),
    RateTopicData('cereal_first', '🥣', 'Cereal before milk'),
    RateTopicData('fries_ice_cream', '🍟', 'Fries dipped in ice cream'),
    RateTopicData('mango_salt', '🥭', 'Raw mango with salt'),
    RateTopicData('chocolate_chilli', '🌶️', 'Chilli chocolate'),
    RateTopicData('ketchup_maggi', '🍅', 'Ketchup on noodles'),
    RateTopicData('sweet_popcorn', '🍿', 'Sweet popcorn over salted'),
    RateTopicData('raisins_biryani', '🍇', 'Raisins in biryani'),
    RateTopicData('mint_chocolate', '🌿', 'Mint chocolate'),
    RateTopicData('coffee_ice_cream', '☕', 'Coffee ice cream'),
    RateTopicData('fruit_cake', '🍰', 'Fruit cake'),
    RateTopicData('cold_coffee', '🧊', 'Cold coffee'),
    RateTopicData('filter_coffee', '🥛', 'South Indian filter coffee'),
    RateTopicData('espresso', '☕', 'Espresso shots'),
    RateTopicData('cappuccino', '☕', 'Cappuccino'),
    RateTopicData('iced_latte', '🧋', 'Iced lattes'),
    RateTopicData('green_tea', '🍵', 'Green tea'),
    RateTopicData('bubble_tea', '🧋', 'Bubble tea'),
    RateTopicData('matcha', '🍵', 'Matcha'),
    RateTopicData('masala_chai', '🫖', 'Masala chai'),
    RateTopicData('kulhad_chai', '🍵', 'Chai in a kulhad'),
    RateTopicData('herbal_tea', '🌼', 'Herbal tea'),
    RateTopicData('hot_chocolate', '🍫', 'Hot chocolate'),
    RateTopicData('lassi', '🥛', 'Lassi'),
    RateTopicData('buttermilk', '🥛', 'Chaas'),
    RateTopicData('nimbu_pani', '🍋', 'Nimbu pani'),
    RateTopicData('coconut_water', '🥥', 'Coconut water'),
    RateTopicData('sugarcane_juice', '🎋', 'Sugarcane juice'),
    RateTopicData('fresh_juice', '🍊', 'Fresh juice'),
    RateTopicData('smoothies', '🍓', 'Smoothies'),
    RateTopicData('milkshakes', '🥤', 'Milkshakes'),
    RateTopicData('mocktails', '🍹', 'Mocktails'),
    RateTopicData('soda', '🥤', 'Fizzy soda'),
    RateTopicData('sparkling_water', '💧', 'Sparkling water'),
    RateTopicData('energy_drinks', '⚡', 'Energy drinks'),
    RateTopicData('kombucha', '🫙', 'Kombucha'),
    RateTopicData('cold_brew', '🧊', 'Cold brew'),
    RateTopicData('decaf', '☕', 'Decaf coffee'),
    RateTopicData('sugar_in_tea', '🍬', 'Extra sugar in tea'),
    RateTopicData('black_coffee', '☕', 'Black coffee'),
    RateTopicData('iced_tea', '🍋', 'Iced tea'),
    RateTopicData('haldi_doodh', '🥛', 'Turmeric milk'),
    RateTopicData('rose_milk', '🌹', 'Rose milk'),
    RateTopicData('badam_milk', '🥛', 'Badam milk'),
    RateTopicData('jaljeera', '🌿', 'Jaljeera'),
    RateTopicData('aam_panna', '🥭', 'Aam panna'),
    RateTopicData('drinking_water', '💧', 'Drinking 3 litres of water'),
    RateTopicData('early_bird', '🐦', 'Being an early bird'),
    RateTopicData('night_owl', '🦉', 'Staying up late'),
    RateTopicData('naps', '😴', 'Afternoon naps'),
    RateTopicData('snooze_button', '⏰', 'Hitting snooze'),
    RateTopicData('making_bed', '🛏️', 'Making the bed daily'),
    RateTopicData('to_do_lists', '📝', 'To-do lists'),
    RateTopicData('journaling', '📓', 'Journaling'),
    RateTopicData('meditation', '🧘', 'Meditation'),
    RateTopicData('morning_walks', '🚶', 'Morning walks'),
    RateTopicData('running', '🏃', 'Running'),
    RateTopicData('yoga', '🧘', 'Yoga'),
    RateTopicData('cycling', '🚲', 'Cycling'),
    RateTopicData('swimming', '🏊', 'Swimming'),
    RateTopicData('hiking', '🥾', 'Hiking'),
    RateTopicData('dancing_home', '💃', 'Dancing alone at home'),
    RateTopicData('singing_shower', '🚿', 'Singing in the shower'),
    RateTopicData('cold_showers', '🥶', 'Cold showers'),
    RateTopicData('long_baths', '🛁', 'Long baths'),
    RateTopicData('skincare', '🧴', 'Skincare routines'),
    RateTopicData('nail_painting', '💅', 'Painting nails'),
    RateTopicData('hair_experiments', '💇', 'Hair experiments'),
    RateTopicData('tattoos', '🖋️', 'Tattoos'),
    RateTopicData('piercings', '💎', 'Piercings'),
    RateTopicData('being_punctual', '⏰', 'Being on time'),
    RateTopicData('being_late', '🐢', 'Being fashionably late'),
    RateTopicData('planning_ahead', '📋', 'Planning everything ahead'),
    RateTopicData('spontaneity', '🎲', 'Spontaneous plans'),
    RateTopicData('procrastination', '🕰️', 'Procrastinating'),
    RateTopicData('multitasking', '🤹', 'Multitasking'),
    RateTopicData('cleaning', '🧹', 'Cleaning the house'),
    RateTopicData('decluttering', '📦', 'Decluttering'),
    RateTopicData('laundry', '🧺', 'Doing laundry'),
    RateTopicData('ironing', '👔', 'Ironing clothes'),
    RateTopicData('folding_clothes', '👕', 'Folding clothes'),
    RateTopicData('grocery_shopping', '🛒', 'Grocery shopping'),
    RateTopicData('cooking_daily', '🍳', 'Cooking every day'),
    RateTopicData('gardening', '🌱', 'Gardening'),
    RateTopicData('houseplants', '🪴', 'Houseplants'),
    RateTopicData('dish_duty', '🍽️', 'Dish duty'),
    RateTopicData('taking_trash_out', '🗑️', 'Taking out the trash'),
    RateTopicData('vacuuming', '🧹', 'Vacuuming'),
    RateTopicData('organizing_closet', '👚', 'Organizing the closet'),
    RateTopicData('budgeting', '💰', 'Budgeting'),
    RateTopicData('saving_money', '🐷', 'Saving money'),
    RateTopicData('online_shopping', '📦', 'Online shopping'),
    RateTopicData('window_shopping', '🪟', 'Window shopping'),
    RateTopicData('thrift_shopping', '👕', 'Thrift shopping'),
    RateTopicData('bargaining', '💬', 'Bargaining at markets'),
    RateTopicData('sales_hunting', '🏷️', 'Hunting for sales'),
    RateTopicData('impulse_buys', '💸', 'Impulse buying'),
    RateTopicData('collecting', '🗃️', 'Collecting things'),
    RateTopicData('painting', '🎨', 'Painting'),
    RateTopicData('drawing', '✏️', 'Drawing'),
    RateTopicData('photography', '📷', 'Photography'),
    RateTopicData('writing', '✍️', 'Creative writing'),
    RateTopicData('poetry', '📜', 'Poetry'),
    RateTopicData('knitting', '🧶', 'Knitting'),
    RateTopicData('pottery', '🏺', 'Pottery'),
    RateTopicData('calligraphy', '🖋️', 'Calligraphy'),
    RateTopicData('scrapbooking', '📒', 'Scrapbooking'),
    RateTopicData('diy_projects', '🛠️', 'DIY projects'),
    RateTopicData('woodworking', '🪚', 'Woodworking'),
    RateTopicData('lego', '🧱', 'Building Lego'),
    RateTopicData('jigsaw_puzzles', '🧩', 'Jigsaw puzzles'),
    RateTopicData('crosswords', '📰', 'Crosswords'),
    RateTopicData('sudoku', '🔢', 'Sudoku'),
    RateTopicData('chess', '♟️', 'Chess'),
    RateTopicData('board_games', '🎲', 'Board games'),
    RateTopicData('card_games', '🃏', 'Card games'),
    RateTopicData('ludo', '🎲', 'Ludo'),
    RateTopicData('carrom', '⚪', 'Carrom'),
    RateTopicData('monopoly', '🏠', 'Monopoly'),
    RateTopicData('uno', '🃏', 'UNO'),
    RateTopicData('mobile_games', '📱', 'Mobile games'),
    RateTopicData('console_gaming', '🎮', 'Console gaming'),
    RateTopicData('pc_gaming', '🖥️', 'PC gaming'),
    RateTopicData('retro_games', '👾', 'Retro games'),
    RateTopicData('vr_games', '🥽', 'VR games'),
    RateTopicData('esports', '🏆', 'Watching esports'),
    RateTopicData('arcades', '🕹️', 'Arcades'),
    RateTopicData('bowling', '🎳', 'Bowling'),
    RateTopicData('mini_golf', '⛳', 'Mini golf'),
    RateTopicData('escape_rooms', '🔐', 'Escape rooms'),
    RateTopicData('trivia_nights', '❓', 'Trivia nights'),
    RateTopicData('karaoke_duets', '🎤', 'Karaoke duets'),
    RateTopicData('stand_up_comedy', '😂', 'Stand-up comedy shows'),
    RateTopicData('magic_shows', '🪄', 'Magic shows'),
    RateTopicData('theatre', '🎭', 'Theatre plays'),
    RateTopicData('musicals', '🎶', 'Musicals'),
    RateTopicData('ballet', '🩰', 'Ballet'),
    RateTopicData('opera', '🎻', 'Opera'),
    RateTopicData('concerts', '🎤', 'Live concerts'),
    RateTopicData('music_festivals', '🎪', 'Music festivals'),
    RateTopicData('art_galleries', '🖼️', 'Art galleries'),
    RateTopicData('museums', '🏛️', 'Museums'),
    RateTopicData('zoos', '🦒', 'Zoos'),
    RateTopicData('aquariums', '🐠', 'Aquariums'),
    RateTopicData('theme_parks', '🎢', 'Theme parks'),
    RateTopicData('roller_coasters', '🎢', 'Roller coasters'),
    RateTopicData('water_parks', '💦', 'Water parks'),
    RateTopicData('haunted_houses', '🏚️', 'Haunted houses'),
    RateTopicData('ferris_wheels', '🎡', 'Ferris wheels'),
    RateTopicData('fairs', '🎪', 'Local fairs'),
    RateTopicData('circus', '🎪', 'Circus shows'),
    RateTopicData('picnics', '🧺', 'Picnics'),
    RateTopicData('bonfires', '🔥', 'Bonfires'),
    RateTopicData('stargazing', '🌌', 'Stargazing'),
    RateTopicData('sunrises', '🌅', 'Watching sunrises'),
    RateTopicData('sunsets', '🌇', 'Watching sunsets'),
    RateTopicData('bird_watching', '🐦', 'Bird watching'),
    RateTopicData('fishing', '🎣', 'Fishing'),
    RateTopicData('kayaking', '🛶', 'Kayaking'),
    RateTopicData('surfing', '🏄', 'Surfing'),
    RateTopicData('scuba_diving', '🤿', 'Scuba diving'),
    RateTopicData('snorkeling', '🤿', 'Snorkeling'),
    RateTopicData('skydiving', '🪂', 'Skydiving'),
    RateTopicData('bungee', '🪢', 'Bungee jumping'),
    RateTopicData('paragliding', '🪂', 'Paragliding'),
    RateTopicData('rock_climbing', '🧗', 'Rock climbing'),
    RateTopicData('river_rafting', '🚣', 'River rafting'),
    RateTopicData('skiing', '⛷️', 'Skiing'),
    RateTopicData('ice_skating', '⛸️', 'Ice skating'),
    RateTopicData('roller_skating', '🛼', 'Roller skating'),
    RateTopicData('skateboarding', '🛹', 'Skateboarding'),
    RateTopicData('horse_riding', '🐴', 'Horse riding'),
    RateTopicData('zip_lining', '🪢', 'Zip-lining'),
    RateTopicData('trekking', '🏔️', 'Himalayan treks'),
    RateTopicData('glamping', '🛖', 'Glamping'),
    RateTopicData('road_trip_snacks', '🍟', 'Road trip snacks'),
    RateTopicData('backpacking', '🎒', 'Backpacking'),
    RateTopicData('solo_travel', '🧳', 'Solo travel'),
    RateTopicData('group_trips', '👥', 'Group trips'),
    RateTopicData('cruises', '🚢', 'Cruises'),
    RateTopicData('train_journeys', '🚆', 'Long train journeys'),
    RateTopicData('flying', '✈️', 'Flying'),
    RateTopicData('window_seat', '🪟', 'Window seats'),
    RateTopicData('aisle_seat', '🚶', 'Aisle seats'),
    RateTopicData('airport_waiting', '🛫', 'Waiting at airports'),
    RateTopicData('packing_bags', '🧳', 'Packing bags'),
    RateTopicData('unpacking', '📦', 'Unpacking after trips'),
    RateTopicData('hotel_breakfast', '🍳', 'Hotel breakfast buffets'),
    RateTopicData('hostels', '🛏️', 'Staying in hostels'),
    RateTopicData('homestays', '🏡', 'Homestays'),
    RateTopicData('tourist_spots', '📸', 'Touristy spots'),
    RateTopicData('hidden_gems', '💎', 'Finding hidden gems'),
    RateTopicData('souvenirs', '🧲', 'Buying souvenirs'),
    RateTopicData('travel_vlogs', '🎥', 'Travel vlogs'),
    RateTopicData('learning_languages', '🗣️', 'Learning new languages'),
    RateTopicData('history_trivia', '🏺', 'History facts'),
    RateTopicData('science_docs', '🔬', 'Science documentaries'),
    RateTopicData('space_facts', '🚀', 'Space facts'),
    RateTopicData('true_crime', '🕵️', 'True crime podcasts'),
    RateTopicData('podcasts', '🎧', 'Podcasts'),
    RateTopicData('audiobooks', '🎧', 'Audiobooks'),
    RateTopicData('e_readers', '📱', 'E-readers'),
    RateTopicData('paperbacks', '📖', 'Paperback books'),
    RateTopicData('comics', '💥', 'Comics'),
    RateTopicData('manga', '🍥', 'Manga'),
    RateTopicData('poetry_books', '📚', 'Poetry collections'),
    RateTopicData('self_help', '🧠', 'Self-help books'),
    RateTopicData('romance_novels', '💕', 'Romance novels'),
    RateTopicData('mystery_novels', '🔍', 'Mystery novels'),
    RateTopicData('fantasy_books', '🐉', 'Fantasy books'),
    RateTopicData('sci_fi_books', '🚀', 'Sci-fi books'),
    RateTopicData('biographies', '📘', 'Biographies'),
    RateTopicData('newspapers', '📰', 'Reading the newspaper'),
    RateTopicData('libraries', '🏛️', 'Libraries'),
    RateTopicData('bookstores', '📚', 'Bookstores'),
    RateTopicData('book_clubs', '☕', 'Book clubs'),
    RateTopicData('pop_music', '🎤', 'Pop music'),
    RateTopicData('rock_music', '🎸', 'Rock music'),
    RateTopicData('metal_music', '🤘', 'Heavy metal'),
    RateTopicData('jazz', '🎷', 'Jazz'),
    RateTopicData('blues', '🎺', 'Blues'),
    RateTopicData('classical_music', '🎻', 'Western classical music'),
    RateTopicData('hindustani_classical', '🪕', 'Hindustani classical'),
    RateTopicData('carnatic', '🎶', 'Carnatic music'),
    RateTopicData('sufi_music', '🌙', 'Sufi music'),
    RateTopicData('ghazals', '🎙️', 'Ghazals'),
    RateTopicData('qawwali', '👏', 'Qawwali nights'),
    RateTopicData('hip_hop', '🎧', 'Hip-hop'),
    RateTopicData('rap', '🎤', 'Rap battles'),
    RateTopicData('desi_hip_hop', '🔥', 'Desi hip-hop'),
    RateTopicData('edm', '🎛️', 'EDM'),
    RateTopicData('lofi', '🎧', 'Lo-fi beats'),
    RateTopicData('indie_music', '🎸', 'Indie music'),
    RateTopicData('kpop', '💜', 'K-pop'),
    RateTopicData('jpop', '🌸', 'J-pop'),
    RateTopicData('punjabi_songs', '🥁', 'Punjabi songs'),
    RateTopicData('tamil_songs', '🎵', 'Tamil film songs'),
    RateTopicData('latin_music', '💃', 'Latin music'),
    RateTopicData('reggae', '🟢', 'Reggae'),
    RateTopicData('country_music', '🤠', 'Country music'),
    RateTopicData('folk_music', '🪕', 'Folk music'),
    RateTopicData('disco', '🪩', 'Disco'),
    RateTopicData('90s_bollywood', '📼', '90s Bollywood songs'),
    RateTopicData('new_bollywood', '🎶', 'New Bollywood songs'),
    RateTopicData('remixes', '🔀', 'Remixes of old songs'),
    RateTopicData('item_songs', '💃', 'Bollywood dance numbers'),
    RateTopicData('love_ballads', '💕', 'Love ballads'),
    RateTopicData('sad_songs', '😢', 'Sad songs on repeat'),
    RateTopicData('workout_music', '💪', 'Workout playlists'),
    RateTopicData('instrumental', '🎹', 'Instrumental music'),
    RateTopicData('movie_scores', '🎼', 'Movie soundtracks'),
    RateTopicData('video_game_music', '🎮', 'Video game music'),
    RateTopicData('acapella', '🎙️', 'A cappella'),
    RateTopicData('boy_bands', '🕺', 'Boy bands'),
    RateTopicData('girl_groups', '💃', 'Girl groups'),
    RateTopicData('vinyl_records', '💿', 'Vinyl records'),
    RateTopicData('cassettes', '📼', 'Cassette tapes'),
    RateTopicData('radio', '📻', 'FM radio'),
    RateTopicData('music_streaming', '🎵', 'Music streaming apps'),
    RateTopicData('playlist_making', '📝', 'Making playlists'),
    RateTopicData('shuffle_mode', '🔀', 'Shuffle mode'),
    RateTopicData('song_on_repeat', '🔁', 'One song on repeat'),
    RateTopicData('loud_music', '🔊', 'Loud music'),
    RateTopicData('humming', '🎵', 'Humming all day'),
    RateTopicData('air_guitar', '🎸', 'Air guitar'),
    RateTopicData('learning_guitar', '🎸', 'Learning guitar'),
    RateTopicData('piano', '🎹', 'Piano'),
    RateTopicData('drums', '🥁', 'Drums'),
    RateTopicData('violin', '🎻', 'Violin'),
    RateTopicData('flute', '🪈', 'Flute'),
    RateTopicData('tabla', '🥁', 'Tabla'),
    RateTopicData('ukulele', '🪕', 'Ukulele'),
    RateTopicData('antakshari', '🎵', 'Antakshari'),
    RateTopicData('rom_coms', '💕', 'Rom-coms'),
    RateTopicData('action_movies', '💥', 'Action movies'),
    RateTopicData('comedy_movies', '😂', 'Comedy movies'),
    RateTopicData('thrillers', '🔪', 'Thrillers'),
    RateTopicData('psych_thrillers', '🧠', 'Psychological thrillers'),
    RateTopicData('sci_fi_movies', '🚀', 'Sci-fi movies'),
    RateTopicData('fantasy_movies', '🧙', 'Fantasy movies'),
    RateTopicData('superhero_movies', '🦸', 'Superhero movies'),
    RateTopicData('animated_movies', '🧸', 'Animated movies'),
    RateTopicData('anime', '🍥', 'Anime'),
    RateTopicData('documentaries', '🐋', 'Documentaries'),
    RateTopicData('musicals_films', '🎬', 'Movie musicals'),
    RateTopicData('war_movies', '🪖', 'War movies'),
    RateTopicData('westerns', '🤠', 'Westerns'),
    RateTopicData('period_dramas', '👑', 'Period dramas'),
    RateTopicData('mystery_movies', '🔍', 'Whodunit mysteries'),
    RateTopicData('disaster_movies', '🌋', 'Disaster movies'),
    RateTopicData('zombie_movies', '🧟', 'Zombie movies'),
    RateTopicData('slasher_films', '🔪', 'Slasher films'),
    RateTopicData('heist_movies', '💰', 'Heist movies'),
    RateTopicData('spy_movies', '🕵️', 'Spy movies'),
    RateTopicData('sports_movies', '🏆', 'Sports movies'),
    RateTopicData('coming_of_age', '🎒', 'Coming-of-age films'),
    RateTopicData('tearjerkers', '😭', 'Tearjerker movies'),
    RateTopicData('black_white', '🎞️', 'Black-and-white classics'),
    RateTopicData('foreign_films', '🌍', 'Subtitled foreign films'),
    RateTopicData('indie_films', '🎥', 'Indie films'),
    RateTopicData('south_movies', '🎬', 'South Indian blockbusters'),
    RateTopicData('masala_movies', '🌶️', 'Masala entertainers'),
    RateTopicData('movie_sequels', '2️⃣', 'Movie sequels'),
    RateTopicData('remakes', '🔁', 'Remakes'),
    RateTopicData('long_movies', '⏳', 'Three-hour movies'),
    RateTopicData('short_films', '🎞️', 'Short films'),
    RateTopicData('cinema_halls', '🍿', 'Cinema halls'),
    RateTopicData('drive_ins', '🚗', 'Drive-in movies'),
    RateTopicData('movie_marathons', '📺', 'Movie marathons'),
    RateTopicData('midnight_premieres', '🌙', 'Midnight premieres'),
    RateTopicData('spoilers', '🤐', 'Spoilers'),
    RateTopicData('movie_trailers', '🎬', 'Movie trailers'),
    RateTopicData('end_credits', '📜', 'Staying for end credits'),
    RateTopicData('rewatching_movies', '🔁', 'Rewatching favorite movies'),
    RateTopicData('sitcoms', '😂', 'Sitcoms'),
    RateTopicData('k_dramas', '🌸', 'K-dramas'),
    RateTopicData('web_series', '📱', 'Web series'),
    RateTopicData('crime_dramas', '🚨', 'Crime dramas'),
    RateTopicData('soap_operas', '📺', 'Daily soaps'),
    RateTopicData('cooking_competitions', '🍳', 'Cooking competitions'),
    RateTopicData('talent_shows', '🌟', 'Talent shows'),
    RateTopicData('dance_shows', '💃', 'Dance reality shows'),
    RateTopicData('quiz_shows', '❓', 'Quiz shows'),
    RateTopicData('game_shows', '🎰', 'Game shows'),
    RateTopicData('talk_shows', '🛋️', 'Talk shows'),
    RateTopicData('news_channels', '📰', 'News channels'),
    RateTopicData('cartoons', '🐭', 'Cartoons as an adult'),
    RateTopicData('nature_shows', '🦁', 'Nature shows'),
    RateTopicData('binge_watching', '🍿', 'Binge-watching'),
    RateTopicData('weekly_episodes', '📅', 'Waiting for weekly episodes'),
    RateTopicData('dubbed_shows', '🗣️', 'Dubbed shows'),
    RateTopicData('subtitles', '💬', 'Subtitles always on'),
    RateTopicData('autoplay', '▶️', 'Autoplay next episode'),
    RateTopicData('skip_intro', '⏭️', 'Skipping intros'),
    RateTopicData('cliffhangers', '🧗', 'Cliffhangers'),
    RateTopicData('fan_theories', '🧠', 'Fan theories'),
    RateTopicData('award_shows', '🏆', 'Award shows'),
    RateTopicData('celebrity_gossip', '🗞️', 'Celebrity gossip'),
    RateTopicData('youtube', '▶️', 'YouTube rabbit holes'),
    RateTopicData('short_videos', '📱', 'Short-form videos'),
    RateTopicData('memes', '🐸', 'Memes'),
    RateTopicData('reels_making', '🎬', 'Making reels'),
    RateTopicData('instagram', '📸', 'Instagram'),
    RateTopicData('twitter_x', '🐦', 'Microblog scrolling'),
    RateTopicData('whatsapp_groups', '💬', 'Family group chats'),
    RateTopicData('group_chats', '👥', 'Friend group chats'),
    RateTopicData('video_calls', '🎥', 'Video calls'),
    RateTopicData('phone_calls', '📞', 'Phone calls'),
    RateTopicData('texting', '💬', 'Texting'),
    RateTopicData('long_texts', '📜', 'Long paragraph texts'),
    RateTopicData('one_word_replies', '👍', 'One-word replies'),
    RateTopicData('emojis', '😂', 'Emojis'),
    RateTopicData('gifs', '🎞️', 'GIFs'),
    RateTopicData('stickers', '🏷️', 'Chat stickers'),
    RateTopicData('read_receipts', '✅', 'Read receipts'),
    RateTopicData('last_seen', '👀', 'Showing last seen'),
    RateTopicData('seen_zoned', '🙈', 'Being left on read'),
    RateTopicData('dark_mode', '🌑', 'Dark mode'),
    RateTopicData('light_mode', '☀️', 'Light mode'),
    RateTopicData('notifications', '🔔', 'Notifications on'),
    RateTopicData('silent_mode', '🔕', 'Phone on silent'),
    RateTopicData('screen_time', '📵', 'Low screen time'),
    RateTopicData('smartphones', '📱', 'Smartphones'),
    RateTopicData('smartwatches', '⌚', 'Smartwatches'),
    RateTopicData('tablets', '📲', 'Tablets'),
    RateTopicData('laptops', '💻', 'Laptops'),
    RateTopicData('mechanical_keyboards', '⌨️', 'Mechanical keyboards'),
    RateTopicData('gaming_pcs', '🖥️', 'Gaming PCs'),
    RateTopicData('headphones', '🎧', 'Big headphones'),
    RateTopicData('earbuds', '🎧', 'Wireless earbuds'),
    RateTopicData('smart_speakers', '🔊', 'Smart speakers'),
    RateTopicData('smart_home', '🏠', 'Smart home gadgets'),
    RateTopicData('robot_vacuums', '🤖', 'Robot vacuums'),
    RateTopicData('ai_assistants', '🤖', 'AI assistants'),
    RateTopicData('voice_assistants', '🗣️', 'Voice assistants'),
    RateTopicData('selfie_sticks', '🤳', 'Selfie sticks'),
    RateTopicData('instant_cameras', '📷', 'Instant cameras'),
    RateTopicData('drones', '🚁', 'Drones'),
    RateTopicData('vr_headsets', '🥽', 'VR headsets'),
    RateTopicData('electric_cars', '🔋', 'Electric cars'),
    RateTopicData('e_scooters', '🛴', 'E-scooters'),
    RateTopicData('new_phone_every_year', '🆕', 'New phone every year'),
    RateTopicData('cracked_screens', '📱', 'Living with cracked screens'),
    RateTopicData('phone_cases', '📱', 'Fancy phone cases'),
    RateTopicData('power_banks', '🔋', 'Carrying power banks'),
    RateTopicData('battery_anxiety', '🪫', 'Phone at 5% battery'),
    RateTopicData('password_managers', '🔐', 'Password managers'),
    RateTopicData('cloud_backups', '☁️', 'Cloud backups'),
    RateTopicData('online_banking', '🏦', 'Online banking'),
    RateTopicData('upi_payments', '📱', 'UPI payments'),
    RateTopicData('cash_payments', '💵', 'Paying with cash'),
    RateTopicData('coding', '💻', 'Coding'),
    RateTopicData('tech_news', '📰', 'Tech news'),
    RateTopicData('gadget_unboxing', '📦', 'Unboxing videos'),
    RateTopicData('dating_apps', '💘', 'Dating apps'),
    RateTopicData('online_quizzes', '❓', 'Online personality quizzes'),
    RateTopicData('big_cities', '🏙️', 'Big city life'),
    RateTopicData('small_towns', '🏘️', 'Small-town life'),
    RateTopicData('village_life', '🌾', 'Village life'),
    RateTopicData('hill_stations', '⛰️', 'Hill stations'),
    RateTopicData('deserts', '🏜️', 'Desert trips'),
    RateTopicData('forests', '🌲', 'Forest walks'),
    RateTopicData('lakes', '🏞️', 'Lakeside stays'),
    RateTopicData('islands', '🏝️', 'Island getaways'),
    RateTopicData('waterfalls', '💧', 'Waterfalls'),
    RateTopicData('caves', '🕳️', 'Exploring caves'),
    RateTopicData('snowfall', '❄️', 'Snowfall'),
    RateTopicData('rooftops', '🌃', 'Rooftop hangouts'),
    RateTopicData('parks', '🌳', 'City parks'),
    RateTopicData('cafes', '☕', 'Cozy cafés'),
    RateTopicData('malls', '🏬', 'Shopping malls'),
    RateTopicData('night_markets', '🏮', 'Night markets'),
    RateTopicData('flea_markets', '🧺', 'Flea markets'),
    RateTopicData('old_bazaars', '🪔', 'Old bazaars'),
    RateTopicData('historic_forts', '🏰', 'Historic forts'),
    RateTopicData('palaces', '👑', 'Palaces'),
    RateTopicData('ruins', '🗿', 'Ancient ruins'),
    RateTopicData('lighthouses', '🗼', 'Lighthouses'),
    RateTopicData('bridges', '🌉', 'Bridges at night'),
    RateTopicData('botanical_gardens', '🌺', 'Botanical gardens'),
    RateTopicData('farms', '🚜', 'Farm visits'),
    RateTopicData('vineyards', '🍇', 'Grape farms'),
    RateTopicData('tea_estates', '🍵', 'Tea estates'),
    RateTopicData('national_parks', '🦁', 'National parks'),
    RateTopicData('safaris', '🐘', 'Wildlife safaris'),
    RateTopicData('goa', '🏖️', 'Goa'),
    RateTopicData('ladakh', '🏔️', 'Ladakh'),
    RateTopicData('kerala', '🌴', 'Kerala backwaters'),
    RateTopicData('rajasthan', '🐪', 'Rajasthan'),
    RateTopicData('mumbai', '🌊', 'Mumbai'),
    RateTopicData('delhi', '🕌', 'Delhi'),
    RateTopicData('bengaluru', '🌳', 'Bengaluru weather'),
    RateTopicData('kolkata', '🚋', 'Kolkata'),
    RateTopicData('paris', '🗼', 'Paris'),
    RateTopicData('tokyo', '🗼', 'Tokyo'),
    RateTopicData('new_york', '🗽', 'New York'),
    RateTopicData('london', '🎡', 'London'),
    RateTopicData('bali', '🌺', 'Bali'),
    RateTopicData('switzerland', '🇨🇭', 'Switzerland'),
    RateTopicData('iceland', '🌋', 'Iceland'),
    RateTopicData('dubai', '🏙️', 'Dubai'),
    RateTopicData('singapore', '🦁', 'Singapore'),
    RateTopicData('maldives', '🏝️', 'The Maldives'),
    RateTopicData('hot_weather', '🥵', 'Hot weather'),
    RateTopicData('cold_weather', '🥶', 'Cold weather'),
    RateTopicData('humid_days', '💦', 'Humid days'),
    RateTopicData('windy_days', '🌬️', 'Windy days'),
    RateTopicData('foggy_mornings', '🌫️', 'Foggy mornings'),
    RateTopicData('thunderstorms', '⛈️', 'Thunderstorms'),
    RateTopicData('cloudy_days', '☁️', 'Cloudy days'),
    RateTopicData('sunny_days', '☀️', 'Sunny days'),
    RateTopicData('drizzle', '🌦️', 'Light drizzle'),
    RateTopicData('heatwaves', '🔥', 'Heatwaves'),
    RateTopicData('first_rain', '🌧️', 'Smell of first rain'),
    RateTopicData('umbrellas', '☂️', 'Carrying umbrellas'),
    RateTopicData('raincoats', '🧥', 'Raincoats'),
    RateTopicData('rainbows', '🌈', 'Rainbows'),
    RateTopicData('full_moon', '🌕', 'Full moon nights'),
    RateTopicData('spring', '🌸', 'Spring'),
    RateTopicData('summer', '☀️', 'Summer'),
    RateTopicData('monsoon', '🌧️', 'Monsoon season'),
    RateTopicData('autumn', '🍂', 'Autumn'),
    RateTopicData('winter', '❄️', 'Winter'),
    RateTopicData('summer_vacations', '🏖️', 'Summer vacations'),
    RateTopicData('winter_breaks', '🎄', 'Winter breaks'),
    RateTopicData('long_weekends', '📅', 'Long weekends'),
    RateTopicData('mondays', '😩', 'Mondays'),
    RateTopicData('fridays', '🎉', 'Friday evenings'),
    RateTopicData('sundays', '☀️', 'Sundays'),
    RateTopicData('birthdays', '🎂', 'Birthdays'),
    RateTopicData('own_birthday', '🥳', 'Celebrating my own birthday'),
    RateTopicData('new_years_eve', '🎆', "New Year's Eve"),
    RateTopicData('new_year_resolutions', '📝', 'New Year resolutions'),
    RateTopicData('diwali', '🪔', 'Diwali'),
    RateTopicData('holi', '🎨', 'Holi'),
    RateTopicData('christmas', '🎄', 'Christmas'),
    RateTopicData('eid', '🌙', 'Eid feasts'),
    RateTopicData('navratri', '💃', 'Navratri garba'),
    RateTopicData('durga_puja', '🎊', 'Durga Puja pandal hopping'),
    RateTopicData('ganesh_festival', '🎉', 'Ganeshotsav processions'),
    RateTopicData('onam', '🌼', 'Onam sadhya'),
    RateTopicData('pongal', '🍚', 'Pongal'),
    RateTopicData('lohri', '🔥', 'Lohri bonfires'),
    RateTopicData('kite_festival', '🪁', 'Kite festival'),
    RateTopicData('halloween', '🎃', 'Halloween'),
    RateTopicData('valentines_day', '💘', "Valentine's Day"),
    RateTopicData('friendship_day', '🤝', 'Friendship Day'),
    RateTopicData('lunar_new_year', '🏮', 'Lunar New Year'),
    RateTopicData('thanksgiving', '🦃', 'Thanksgiving dinners'),
    RateTopicData('fireworks', '🎆', 'Fireworks'),
    RateTopicData('festive_sweets', '🍬', 'Festive sweets'),
    RateTopicData('gift_exchanges', '🎁', 'Gift exchanges'),
    RateTopicData('secret_santa', '🎅', 'Secret Santa'),
    RateTopicData('family_functions', '👨‍👩‍👧', 'Family functions'),
    RateTopicData('house_parties', '🏠', 'House parties'),
    RateTopicData('weddings_dance', '💃', 'Dancing at weddings'),
    RateTopicData('sangeet', '🎶', 'Sangeet nights'),
    RateTopicData('mehendi', '🌿', 'Mehendi ceremonies'),
    RateTopicData('baby_showers', '🍼', 'Baby showers'),
    RateTopicData('farewells', '👋', 'Farewell parties'),
    RateTopicData('reunions', '🫂', 'School reunions'),
    RateTopicData('anniversaries', '💞', 'Anniversaries'),
    RateTopicData('football', '⚽', 'Football'),
    RateTopicData('watching_football', '📺', 'Watching football'),
    RateTopicData('basketball', '🏀', 'Basketball'),
    RateTopicData('tennis', '🎾', 'Tennis'),
    RateTopicData('badminton', '🏸', 'Badminton'),
    RateTopicData('table_tennis', '🏓', 'Table tennis'),
    RateTopicData('volleyball', '🏐', 'Volleyball'),
    RateTopicData('hockey', '🏑', 'Hockey'),
    RateTopicData('kabaddi', '🤼', 'Kabaddi'),
    RateTopicData('formula_one', '🏎️', 'Formula 1'),
    RateTopicData('wrestling', '🤼', 'Pro wrestling'),
    RateTopicData('boxing', '🥊', 'Boxing'),
    RateTopicData('martial_arts', '🥋', 'Martial arts'),
    RateTopicData('golf', '⛳', 'Golf'),
    RateTopicData('baseball', '⚾', 'Baseball'),
    RateTopicData('american_football', '🏈', 'American football'),
    RateTopicData('rugby', '🏉', 'Rugby'),
    RateTopicData('olympics', '🥇', 'The Olympics'),
    RateTopicData('ipl', '🏏', 'IPL season'),
    RateTopicData('test_cricket', '🏏', 'Test cricket'),
    RateTopicData('gully_cricket', '🏏', 'Gully cricket'),
    RateTopicData('fantasy_leagues', '📊', 'Fantasy sports leagues'),
    RateTopicData('marathons', '🏅', 'Marathons'),
    RateTopicData('zumba', '💃', 'Zumba'),
    RateTopicData('pilates', '🤸', 'Pilates'),
    RateTopicData('crossfit', '🏋️', 'CrossFit'),
    RateTopicData('home_workouts', '🏠', 'Home workouts'),
    RateTopicData('step_counting', '👟', 'Counting steps'),
    RateTopicData('sports_jerseys', '👕', 'Wearing sports jerseys'),
    RateTopicData('stadium_crowds', '🏟️', 'Stadium crowds'),
    RateTopicData('penalty_shootouts', '🥅', 'Penalty shootouts'),
    RateTopicData('super_overs', '🏏', 'Super overs'),
    RateTopicData('jeans', '👖', 'Jeans'),
    RateTopicData('sweatpants', '🩳', 'Sweatpants'),
    RateTopicData('hoodies', '🧥', 'Hoodies'),
    RateTopicData('oversized_tees', '👕', 'Oversized tees'),
    RateTopicData('formal_wear', '👔', 'Formal wear'),
    RateTopicData('suits', '🤵', 'Suits'),
    RateTopicData('sarees', '🥻', 'Sarees'),
    RateTopicData('kurtas', '👘', 'Kurtas'),
    RateTopicData('ethnic_wear', '🪔', 'Ethnic wear'),
    RateTopicData('dresses', '👗', 'Dresses'),
    RateTopicData('shorts', '🩳', 'Shorts'),
    RateTopicData('sneakers', '👟', 'Sneakers'),
    RateTopicData('heels', '👠', 'Heels'),
    RateTopicData('sandals', '🩴', 'Sandals'),
    RateTopicData('flip_flops', '🩴', 'Flip-flops'),
    RateTopicData('boots', '🥾', 'Boots'),
    RateTopicData('socks_sandals', '🧦', 'Socks with sandals'),
    RateTopicData('caps', '🧢', 'Caps'),
    RateTopicData('hats', '👒', 'Sun hats'),
    RateTopicData('sunglasses', '🕶️', 'Sunglasses'),
    RateTopicData('watches', '⌚', 'Watches'),
    RateTopicData('jewelry', '💍', 'Jewelry'),
    RateTopicData('minimal_jewelry', '✨', 'Minimal jewelry'),
    RateTopicData('statement_earrings', '💎', 'Statement earrings'),
    RateTopicData('scarves', '🧣', 'Scarves'),
    RateTopicData('backpacks', '🎒', 'Backpacks'),
    RateTopicData('tote_bags', '👜', 'Tote bags'),
    RateTopicData('perfume', '🌸', 'Perfume'),
    RateTopicData('matching_outfits', '👯', 'Matching outfits'),
    RateTopicData('all_black', '🖤', 'All-black outfits'),
    RateTopicData('bright_colors', '🌈', 'Bright colors'),
    RateTopicData('pastels', '🩷', 'Pastel colors'),
    RateTopicData('neon', '💚', 'Neon colors'),
    RateTopicData('floral_prints', '🌸', 'Floral prints'),
    RateTopicData('stripes', '🦓', 'Stripes'),
    RateTopicData('polka_dots', '⚫', 'Polka dots'),
    RateTopicData('leopard_print', '🐆', 'Animal prints'),
    RateTopicData('denim_on_denim', '👖', 'Denim on denim'),
    RateTopicData('vintage_fashion', '📼', 'Vintage fashion'),
    RateTopicData('fast_fashion', '🛍️', 'Fast fashion'),
    RateTopicData('sustainable_fashion', '♻️', 'Sustainable fashion'),
    RateTopicData('dressing_up', '✨', 'Dressing up'),
    RateTopicData('pajamas_all_day', '🛌', 'Pajamas all day'),
    RateTopicData('uniforms', '👔', 'Uniforms'),
    RateTopicData('costume_parties', '🎭', 'Costume parties'),
    RateTopicData('beards', '🧔', 'Beards'),
    RateTopicData('long_hair', '💇', 'Long hair'),
    RateTopicData('short_hair', '💇', 'Short hair'),
    RateTopicData('hair_dye', '🌈', 'Colored hair'),
    RateTopicData('makeup', '💄', 'Makeup'),
    RateTopicData('nail_art', '💅', 'Nail art'),
    RateTopicData('glasses', '👓', 'Wearing glasses'),
    RateTopicData('contact_lenses', '👁️', 'Contact lenses'),
    RateTopicData('texting_first', '📱', 'Texting first'),
    RateTopicData('calling_first', '📞', 'Calling first'),
    RateTopicData('double_texting', '💬', 'Double texting'),
    RateTopicData('good_morning_texts', '🌅', 'Good-morning texts'),
    RateTopicData('goodnight_calls', '🌙', 'Goodnight calls'),
    RateTopicData('love_letters', '💌', 'Handwritten love letters'),
    RateTopicData('pda', '💑', 'Holding hands in public'),
    RateTopicData('cheesy_pickup_lines', '🧀', 'Cheesy pickup lines'),
    RateTopicData('couple_nicknames', '🍯', 'Cute couple nicknames'),
    RateTopicData('matching_bios', '📝', 'Matching profile bios'),
    RateTopicData('couple_photos', '📸', 'Couple photos online'),
    RateTopicData('first_date_nerves', '😬', 'First-date nerves'),
    RateTopicData('blind_dates', '🙈', 'Blind dates'),
    RateTopicData('double_dates', '👥', 'Double dates'),
    RateTopicData('splitting_bill', '🧾', 'Splitting the bill'),
    RateTopicData('surprise_gifts', '🎁', 'Surprise gifts'),
    RateTopicData('flowers_gift', '💐', 'Getting flowers'),
    RateTopicData('chocolates_gift', '🍫', 'Getting chocolates'),
    RateTopicData('handmade_gifts', '🧶', 'Handmade gifts'),
    RateTopicData('gift_cards', '💳', 'Gift cards'),
    RateTopicData('anniversary_trips', '✈️', 'Anniversary trips'),
    RateTopicData('candlelight_dinners', '🕯️', 'Candlelight dinners'),
    RateTopicData('slow_dancing', '💃', 'Slow dancing'),
    RateTopicData('movie_dates', '🎬', 'Movie dates'),
    RateTopicData('coffee_dates', '☕', 'Coffee dates'),
    RateTopicData('long_walks', '🚶', 'Long walks'),
    RateTopicData('deep_talks', '🌊', 'Deep 2 AM talks'),
    RateTopicData('small_talk', '☁️', 'Small talk'),
    RateTopicData('awkward_silences', '😶', 'Awkward silences'),
    RateTopicData('inside_jokes', '😂', 'Inside jokes'),
    RateTopicData('sarcasm', '🙃', 'Sarcasm'),
    RateTopicData('puns', '🥁', 'Puns'),
    RateTopicData('dad_jokes', '🤦', 'Dad jokes'),
    RateTopicData('pranks', '🎭', 'Pranks'),
    RateTopicData('being_teased', '😏', 'Being teased'),
    RateTopicData('compliments', '💐', 'Getting compliments'),
    RateTopicData('public_speaking', '🎤', 'Public speaking'),
    RateTopicData('meeting_new_people', '👋', 'Meeting new people'),
    RateTopicData('networking', '🤝', 'Networking events'),
    RateTopicData('big_parties', '🎉', 'Big parties'),
    RateTopicData('small_gatherings', '🫂', 'Small gatherings'),
    RateTopicData('staying_in', '🏠', 'Staying in on Friday'),
    RateTopicData('unplanned_guests', '🚪', 'Unplanned guests'),
    RateTopicData('hosting_dinners', '🍽️', 'Hosting dinners'),
    RateTopicData('potlucks', '🥘', 'Potlucks'),
    RateTopicData('group_photos', '📸', 'Group photos'),
    RateTopicData('birthday_singing', '🎂', 'Being sung happy birthday'),
    RateTopicData(
        'being_center_attention', '🌟', 'Being the center of attention'),
    RateTopicData('phone_free_dinners', '📵', 'Phone-free dinners'),
    RateTopicData('oversharing', '🗣️', 'Oversharing'),
    RateTopicData('voice_messages_long', '🎙️', 'Five-minute voice messages'),
    RateTopicData('spontaneous_trips', '🎲', 'Spontaneous trips'),
    RateTopicData('early_dinners', '🕕', 'Early dinners'),
    RateTopicData('late_dinners', '🕙', 'Late dinners'),
    RateTopicData('queues', '🧍', 'Standing in queues'),
    RateTopicData('crowds', '👥', 'Crowded places'),
    RateTopicData('traffic', '🚦', 'Traffic jams'),
    RateTopicData('honking', '📯', 'Constant honking'),
    RateTopicData('public_transport', '🚇', 'Public transport'),
    RateTopicData('metro_rides', '🚇', 'Metro rides'),
    RateTopicData('auto_rickshaws', '🛺', 'Auto rickshaw rides'),
    RateTopicData('cab_rides', '🚕', 'Cab rides'),
    RateTopicData('driving', '🚗', 'Driving'),
    RateTopicData('long_drives', '🛣️', 'Late-night long drives'),
    RateTopicData('bikes', '🏍️', 'Motorbike rides'),
    RateTopicData('scooters', '🛵', 'Scooter rides'),
    RateTopicData('walking_everywhere', '🚶', 'Walking everywhere'),
    RateTopicData('elevators_small_talk', '🛗', 'Small talk in elevators'),
    RateTopicData('office_life', '🏢', 'Office life'),
    RateTopicData('work_from_home', '🏠', 'Working from home'),
    RateTopicData('meetings', '📅', 'Meetings'),
    RateTopicData('emails', '📧', 'Replying to emails'),
    RateTopicData('deadlines', '⏳', 'Deadlines'),
    RateTopicData('side_hustles', '💼', 'Side hustles'),
    RateTopicData('studying', '📚', 'Studying'),
    RateTopicData('exams', '📝', 'Exams'),
    RateTopicData('group_projects', '👥', 'Group projects'),
    RateTopicData('online_classes', '💻', 'Online classes'),
    RateTopicData('school_memories', '🏫', 'School memories'),
    RateTopicData('college_canteen', '🍟', 'College canteen days'),
    RateTopicData('hostel_life', '🛏️', 'Hostel life'),
    RateTopicData('pets_in_bed', '🛏️', 'Pets sleeping in the bed'),
    RateTopicData('puppies', '🐶', 'Puppies'),
    RateTopicData('kittens', '🐱', 'Kittens'),
    RateTopicData('rabbits', '🐰', 'Rabbits'),
    RateTopicData('hamsters', '🐹', 'Hamsters'),
    RateTopicData('parrots', '🦜', 'Parrots'),
    RateTopicData('fish_tanks', '🐠', 'Fish tanks'),
    RateTopicData('turtles', '🐢', 'Turtles'),
    RateTopicData('horses', '🐴', 'Horses'),
    RateTopicData('cows', '🐄', 'Cows'),
    RateTopicData('goats', '🐐', 'Goats'),
    RateTopicData('pandas', '🐼', 'Pandas'),
    RateTopicData('penguins', '🐧', 'Penguins'),
    RateTopicData('otters', '🦦', 'Otters'),
    RateTopicData('elephants', '🐘', 'Elephants'),
    RateTopicData('monkeys', '🐒', 'Monkeys'),
    RateTopicData('squirrels', '🐿️', 'Squirrels'),
    RateTopicData('pigeons', '🕊️', 'Pigeons'),
    RateTopicData('butterflies', '🦋', 'Butterflies'),
    RateTopicData('bees', '🐝', 'Bees'),
    RateTopicData('spiders', '🕷️', 'Spiders'),
    RateTopicData('lizards', '🦎', 'Lizards'),
    RateTopicData('snakes', '🐍', 'Snakes'),
    RateTopicData('cockroaches', '🪳', 'Cockroaches'),
    RateTopicData('mosquitoes', '🦟', 'Mosquitoes'),
    RateTopicData('street_dogs', '🐕', 'Feeding street dogs'),
    RateTopicData('dog_parks', '🌳', 'Dog parks'),
    RateTopicData('cat_cafes', '🐈', 'Cat cafés'),
    RateTopicData('pet_costumes', '🎃', 'Pet costumes'),
    RateTopicData('pet_instagram', '📸', 'Pet social media accounts'),
    RateTopicData('pineapple_biryani', '🍍', 'Pineapple in biryani'),
    RateTopicData('cereal_dinner', '🥣', 'Cereal for dinner'),
    RateTopicData('crocs', '🩴', 'Crocs'),
    RateTopicData('socks_in_bed', '🧦', 'Wearing socks in bed'),
    RateTopicData('showers_at_night', '🚿', 'Night showers'),
    RateTopicData('morning_showers', '🌅', 'Morning showers'),
    RateTopicData('toilet_paper_over', '🧻', 'Toilet roll hung over'),
    RateTopicData('reading_endings_first', '📖', 'Reading the ending first'),
    RateTopicData('movie_talkers', '🗣️', 'Talking during movies'),
    RateTopicData('reclining_seats', '💺', 'Reclining plane seats'),
    RateTopicData('speakerphone_public', '📢', 'Speakerphone in public'),
    RateTopicData('open_windows', '🪟', 'Sleeping with windows open'),
    RateTopicData('ac_full_blast', '❄️', 'AC on full blast'),
    RateTopicData('fans_winter', '🌀', 'Fan on in winter'),
    RateTopicData('blanket_summer', '🛌', 'Blanket even in summer'),
    RateTopicData('cold_tea', '🧊', 'Cold leftover tea'),
    RateTopicData('tea_dunking', '🍪', 'Dunking biscuits in chai'),
    RateTopicData('bread_crust', '🍞', 'Bread crusts'),
    RateTopicData('well_done_food', '🔥', 'Extra-crispy everything'),
    RateTopicData('burnt_toast', '🍞', 'Slightly burnt toast'),
    RateTopicData('milk_first_tea', '🥛', 'Milk first in tea'),
    RateTopicData('ketchup_fridge', '🧊', 'Ketchup in the fridge'),
    RateTopicData('wet_hair_bed', '💦', 'Sleeping with wet hair'),
    RateTopicData('alarm_multiple', '⏰', 'Setting ten alarms'),
    RateTopicData('unread_notifications', '🔴', '999 unread notifications'),
    RateTopicData('tabs_open', '🗂️', '50 browser tabs open'),
    RateTopicData('phone_bedside', '📱', 'Phone right by the bed'),
    RateTopicData('caps_lock', '🔠', 'TEXTING IN CAPS'),
    RateTopicData('voice_typing', '🎙️', 'Voice typing'),
    RateTopicData('autocorrect', '✏️', 'Autocorrect'),
    RateTopicData('lowercase_texting', '🔡', 'lowercase-only texting'),
    RateTopicData('punctuation_texts', '❗', 'Full stops in texts'),
    RateTopicData('lol_usage', '😆', 'Saying "lol" a lot'),
    RateTopicData('hahaha', '😂', 'Typing "hahahaha"'),
    RateTopicData('eating_alone', '🍽️', 'Eating alone at restaurants'),
    RateTopicData('movies_alone', '🎬', 'Going to movies alone'),
    RateTopicData('solo_dates', '🧍', 'Solo dates'),
    RateTopicData('singing_aloud', '🎤', 'Singing aloud in public'),
    RateTopicData('talking_to_plants', '🪴', 'Talking to plants'),
    RateTopicData('talking_to_pets', '🐾', 'Talking to pets like humans'),
    RateTopicData('mornings_quiet', '🤫', 'Quiet mornings'),
    RateTopicData('weekends_planned', '📋', 'Fully planned weekends'),
    RateTopicData('lazy_weekends', '🛋️', 'Lazy weekends'),
    RateTopicData('brunch_dates', '🥞', 'Brunch dates'),
    RateTopicData('farmers_markets', '🧺', 'Farmers markets'),
    RateTopicData('ice_cream_winter', '🍦', 'Ice cream in winter'),
    RateTopicData('hot_soup_summer', '🍲', 'Hot soup in summer'),
    RateTopicData('chai_summer', '☀️', 'Chai in peak summer'),
    RateTopicData('spicy_breakfast', '🌶️', 'Spicy breakfast'),
    RateTopicData('dessert_first', '🍰', 'Dessert before dinner'),
    RateTopicData('fruit_on_pizza', '🍑', 'Fruit on savory food'),
    RateTopicData('cheese_chocolate', '🧀', 'Cheese and chocolate together'),
    RateTopicData('sweet_samosa', '🥟', 'Sweet samosa'),
    RateTopicData('mayo_fries', '🍟', 'Mayo with fries'),
    RateTopicData('chips_sandwich', '🥪', 'Chips inside sandwiches'),
    RateTopicData('eating_cake_frosting', '🎂', 'Eating only the frosting'),
    RateTopicData('popcorn_movies', '🍿', 'Popcorn without a movie'),
    RateTopicData('cold_coffee_winter', '🧊', 'Iced coffee in winter'),
    RateTopicData('pizza_fork', '🍴', 'Pizza with a fork'),
    RateTopicData('rice_spoon', '🥄', 'Rice with a spoon'),
    RateTopicData('cake_for_breakfast', '🍰', 'Cake for breakfast'),
    RateTopicData('fortune_cookies', '🥠', 'Fortune cookies'),
    RateTopicData('horoscopes', '♈', 'Daily horoscopes'),
    RateTopicData('tarot_fun', '🔮', 'Tarot cards for fun'),
    RateTopicData('personality_types', '🧩', 'Personality type tests'),
    RateTopicData('superstitions', '🍀', 'Superstitions'),
    RateTopicData('lucky_charms', '🧿', 'Lucky charms'),
    RateTopicData('ghost_stories', '👻', 'Ghost stories'),
    RateTopicData('time_travel_movies', '⏳', 'Time-travel stories'),
    RateTopicData('dinosaurs', '🦖', 'Dinosaurs'),
    RateTopicData('space_exploration', '🚀', 'Space exploration'),
    RateTopicData('ocean_deep', '🌊', 'Deep-sea creatures'),
    RateTopicData('volcanoes', '🌋', 'Volcanoes'),
    RateTopicData('eclipses', '🌑', 'Eclipses'),
    RateTopicData('meteor_showers', '🌠', 'Meteor showers'),
    RateTopicData('northern_lights', '🌌', 'Northern lights'),
    RateTopicData('hot_air_balloons', '🎈', 'Hot air balloons'),
    RateTopicData('cable_cars', '🚡', 'Cable cars'),
    RateTopicData('houseboats', '🛶', 'Houseboats'),
    RateTopicData('treehouses', '🌳', 'Treehouses'),
    RateTopicData('tiny_houses', '🏠', 'Tiny houses'),
    RateTopicData('big_houses', '🏡', 'Huge houses'),
    RateTopicData('minimalism', '⬜', 'Minimalist homes'),
    RateTopicData('maximalism', '🎨', 'Cluttered cozy homes'),
    RateTopicData('fairy_lights', '✨', 'Fairy lights'),
    RateTopicData('scented_candles', '🕯️', 'Scented candles'),
    RateTopicData('bean_bags', '🛋️', 'Bean bags'),
    RateTopicData('hammocks', '🌴', 'Hammocks'),
    RateTopicData('balconies', '🌿', 'Balcony sitting'),
    RateTopicData('bathtubs', '🛁', 'Bathtubs'),
    RateTopicData('open_kitchens', '🍳', 'Open kitchens'),
  ];
}
