// lib/screens/questionnaire/avatar_intro_screen.dart
//
// Shown before the signup questionnaire: explains that the avatar is built
// from the user's answers (not a random pick from a shared set) and shows
// three real examples generated by the same mapping.

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

import '../../core/constants/app_colors.dart';
import '../../services/dicebear_avatar_service.dart';
import 'questionnaire_screen.dart';

class AvatarIntroScreen extends StatelessWidget {
  const AvatarIntroScreen({super.key});

  static final List<({String caption, String url})> _samples = [
    (
      caption: 'Night owl\nLoves reading',
      answers: {
        'gender': 'female',
        'habits': 'Night Owl',
        'interests': ['Reading'],
        'dateOfBirth': '2000-03-12',
      },
      key: 'destined-sample-1',
    ),
    (
      caption: 'Early riser\nTraveller',
      answers: {
        'gender': 'male',
        'habits': 'Early Riser',
        'interests': ['Travel', 'Sports'],
        'dateOfBirth': '1996-04-05',
      },
      key: 'destined-sample-2',
    ),
    (
      caption: 'Artist\nExtrovert',
      answers: {
        'gender': 'female',
        'habits': 'Balanced',
        'interests': ['Art', 'Dancing'],
        'profession': 'Artist',
        'personalityType': 'Extrovert',
        'dateOfBirth': '2001-08-01',
      },
      key: 'destined-sample-3',
    ),
  ]
      .map((s) => (
            caption: s.caption,
            url: DiceBearAvatarService.preview(s.answers, uniqueKey: s.key).url,
          ))
      .toList();

  void _start(BuildContext context) {
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: (_) => const QuestionnaireScreen()),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundDeep,
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(24, 32, 24, 16),
                child: Column(
                  children: [
                    const Text(
                      'BEFORE WE START',
                      style: TextStyle(
                        color: AppColors.brandPink,
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        letterSpacing: 1.2,
                      ),
                    ),
                    const SizedBox(height: 10),
                    const Text(
                      'Your answers become\nyour avatar',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 26,
                        fontWeight: FontWeight.w700,
                        height: 1.2,
                      ),
                    ),
                    const SizedBox(height: 10),
                    const Text(
                      "Your habits, interests and zodiac sign shape a face that's made only for you.",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: AppColors.lavender,
                        fontSize: 15,
                        height: 1.45,
                      ),
                    ),
                    const SizedBox(height: 28),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        for (var i = 0; i < _samples.length; i++)
                          Expanded(
                            child: Padding(
                              padding: EdgeInsets.only(top: i == 1 ? 0 : 14),
                              child: _Sample(
                                url: _samples[i].url,
                                caption: _samples[i].caption,
                                highlighted: i == 1,
                              ),
                            ),
                          ),
                      ],
                    ),
                    const SizedBox(height: 24),
                    IntrinsicHeight(
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          const Expanded(
                            child: _CompareCard(
                              title: 'Other apps',
                              body:
                                  'A random avatar from a small set that thousands of people share.',
                              muted: true,
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: _CompareCard(
                              title: 'Destined',
                              body:
                                  'Built from your answers. No one else gets your face.',
                              faces: [for (final s in _samples) s.url],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'You can switch to a real photo any time.',
                      style: TextStyle(color: AppColors.textMuted, fontSize: 12),
                    ),
                  ],
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
              child: SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton(
                  onPressed: () => _start(context),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.brandPurple,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(28),
                    ),
                  ),
                  child: const Text(
                    "Let's build mine",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Sample extends StatelessWidget {
  final String url;
  final String caption;
  final bool highlighted;

  const _Sample({
    required this.url,
    required this.caption,
    required this.highlighted,
  });

  @override
  Widget build(BuildContext context) {
    final size = highlighted ? 104.0 : 92.0;
    return Column(
      children: [
        Container(
          width: size,
          height: size,
          padding: const EdgeInsets.all(3),
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: highlighted ? AppColors.brandPink : AppColors.surfaceCard,
            boxShadow: highlighted
                ? [
                    BoxShadow(
                      color: AppColors.brandPink.withOpacity(0.35),
                      blurRadius: 24,
                      offset: const Offset(0, 8),
                    ),
                  ]
                : null,
          ),
          child: ClipOval(child: _Net(url: url)),
        ),
        const SizedBox(height: 8),
        Text(
          caption,
          textAlign: TextAlign.center,
          style: const TextStyle(
            color: AppColors.lavender,
            fontSize: 11,
            height: 1.35,
          ),
        ),
      ],
    );
  }
}

class _CompareCard extends StatelessWidget {
  final String title;
  final String body;
  final bool muted;
  final List<String> faces;

  const _CompareCard({
    required this.title,
    required this.body,
    this.muted = false,
    this.faces = const [],
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(14),
        color: muted ? AppColors.surfaceRaised : null,
        gradient: muted
            ? null
            : LinearGradient(
                colors: [
                  AppColors.brandPurple.withOpacity(0.18),
                  AppColors.brandPink.withOpacity(0.10),
                ],
              ),
        border: Border.all(
          color: muted
              ? AppColors.lavender.withOpacity(0.15)
              : AppColors.brandPink.withOpacity(0.4),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              for (var i = 0; i < 3; i++)
                Padding(
                  padding: const EdgeInsets.only(right: 4),
                  child: SizedBox(
                    width: 22,
                    height: 22,
                    child: muted || faces.length <= i
                        ? const DecoratedBox(
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: AppColors.surfaceCard,
                            ),
                          )
                        : ClipOval(child: _Net(url: faces[i])),
                  ),
                ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            title,
            style: TextStyle(
              color: muted ? AppColors.textMuted : Colors.white,
              fontSize: 13,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            body,
            style: TextStyle(
              color: muted ? AppColors.textMuted : Colors.white,
              fontSize: 13,
              height: 1.35,
            ),
          ),
        ],
      ),
    );
  }
}

class _Net extends StatelessWidget {
  final String url;

  const _Net({required this.url});

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
      imageUrl: url,
      fit: BoxFit.cover,
      placeholder: (_, __) => Container(color: AppColors.surfaceCard),
      errorWidget: (_, __, ___) => Container(color: AppColors.surfaceCard),
    );
  }
}
