// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrATas02atbKDEeA1d_K--ZfotrJ2Rbk',
    appId: '1:179987163172:web:0ef1024dcacd78bfad10b1',
    messagingSenderId: '179987163172',
    projectId: 'availchatproject',
    authDomain: 'availchatproject.firebaseapp.com',
    databaseURL: 'https://availchatproject-default-rtdb.firebaseio.com',
    storageBucket: 'availchatproject.firebasestorage.app',
    measurementId: 'G-CEJG6R4SGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QJ3kmRxCagHQOVJ9uEScyVOdkXUHZO0',
    appId: '1:179987163172:android:d371b6f21f4eca07ad10b1',
    messagingSenderId: '179987163172',
    projectId: 'availchatproject',
    databaseURL: 'https://availchatproject-default-rtdb.firebaseio.com',
    storageBucket: 'availchatproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Xsnb-u3LyJeW4vv4Gda_W2NJTvG0Ezc',
    appId: '1:179987163172:ios:ee01292a51f91364ad10b1',
    messagingSenderId: '179987163172',
    projectId: 'availchatproject',
    databaseURL: 'https://availchatproject-default-rtdb.firebaseio.com',
    storageBucket: 'availchatproject.firebasestorage.app',
    androidClientId: '179987163172-acg7r60vcbv3s4eibh7p6q3pcm4mpuvc.apps.googleusercontent.com',
    iosClientId: '179987163172-laaui80vvrl8is3nhhl1l7h3fk34r5uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcDatingAppV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Xsnb-u3LyJeW4vv4Gda_W2NJTvG0Ezc',
    appId: '1:179987163172:ios:ee01292a51f91364ad10b1',
    messagingSenderId: '179987163172',
    projectId: 'availchatproject',
    databaseURL: 'https://availchatproject-default-rtdb.firebaseio.com',
    storageBucket: 'availchatproject.firebasestorage.app',
    androidClientId: '179987163172-acg7r60vcbv3s4eibh7p6q3pcm4mpuvc.apps.googleusercontent.com',
    iosClientId: '179987163172-laaui80vvrl8is3nhhl1l7h3fk34r5uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcDatingAppV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbrATas02atbKDEeA1d_K--ZfotrJ2Rbk',
    appId: '1:179987163172:web:799b3fcd49317574ad10b1',
    messagingSenderId: '179987163172',
    projectId: 'availchatproject',
    authDomain: 'availchatproject.firebaseapp.com',
    databaseURL: 'https://availchatproject-default-rtdb.firebaseio.com',
    storageBucket: 'availchatproject.firebasestorage.app',
    measurementId: 'G-4ET8T1LDGD',
  );
}
